version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
  graphql-server:
    build:
      context: './'
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - mongoURI=mongodb://mongodb:27017/BotCommander-db
